version: '1.0alpha'
services:
  app: 
    build: 
      context: .
      target: dev
    command: 
    - npx migrate deploy
    - npm run dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      
  
  mysql:
    image: mysql:8.0-debian
    restart: always
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      MYSQL_DATABASE: steam
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  mysql:
  app:
networks:
  backend:
    driver: bridge