import type { Metadata } from 'next'
import './globals.css'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import localFont from 'next/font/local'

const MovitvaSans = localFont({
    src: './MotivaSansRegular.ttf',
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${MovitvaSans.className} text-text/main antialiased`}
            >
                {children}
                <TailwindIndicator />
            </body>
        </html>
    )
}
